<a href="https://colab.research.google.com/github/abdurrahmanshidiq/Finance-Analysis/blob/main/7_Python_101_Python_Libraries_for_Data_Analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NUMPY BASICS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [2]:
# Let's create a numpy array from the list "my_list"
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [3]:
type(x)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [5]:
x = np.array([[4, 6, 8, 7], [20, 5, 6, 9]])
x

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(15)
x

array([0.25274429, 0.98509034, 0.57289926, 0.97874439, 0.47721443,
       0.05980272, 0.50482534, 0.64651042, 0.53415611, 0.7945013 ,
       0.35558207, 0.14821373, 0.80624232, 0.38232196, 0.75930662])

In [7]:
# you can create a matrix of random number as well
x = np.random.rand(5,5)
x

array([[0.73830331, 0.18428153, 0.82584807, 0.60051117, 0.24443386],
       [0.58850496, 0.71292044, 0.00217764, 0.13048054, 0.0950982 ],
       [0.0665906 , 0.13206533, 0.76568685, 0.84834919, 0.57924821],
       [0.08443949, 0.77729297, 0.30260518, 0.40902389, 0.03546221],
       [0.94249041, 0.58369569, 0.31647568, 0.92357071, 0.7591344 ]])

In [8]:
# "randn()" normal distribution between 0 and 1
np.random.randn(10)

array([ 0.33054593,  0.45983763, -0.62083818, -0.25643241,  0.5923612 ,
        0.41452755, -0.70614398,  0.26677893, -0.96608035, -0.76307908])

In [9]:
# "randint" is used to generate random integers between upper and lower bounds
np.random.randint(1,10)

6

In [10]:
# "randint" can be used to generate a certain number of random itegers as follows
np.random.randint(1,100,15)

array([35, 88, 99, 96, 20, 16, 78, 14, 35,  6, 53, 52, 55, 57, 66])

In [11]:
# np.arange creates an evenly spaced values within a given interval
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
# Create an evenly spaced values with a step of 5
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [13]:
# create a diagonal of ones and zeros everywhere else
np.eye(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [14]:
# Array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
# Matrices of ones
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
# Array of zeros
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [17]:
num = int(input('Enter a Number : '))

ar = np.random.randint(1,num,20)
ar

Enter a Number : 1000


array([138, 480, 439, 628, 947, 500, 972,  17, 223, 580, 424, 423, 737,
       684, 611, 716, 812, 392, 214, 318])

# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [18]:
# Let's define a one-dimensional array 
my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [19]:
# Get Length of a numpy array
len(x)

8

In [20]:
# Get shape
x.shape

(8,)

In [21]:
# Obtain the datatype
x.dtype

dtype('int64')

In [22]:
# Reshape 1D array into a matrix
z = x.reshape(2,4)
z

array([[-30,   4,  50,  60],
       [ 29,  15,  22,  90]])

In [23]:
# Obtain the maximum element (value)
x.max()

90

In [24]:
# Obtain the minimum element (value)
x.min()

-30

In [25]:
# Obtain the location of the max element
x.argmax()

7

In [26]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

In [27]:
x = np.arange(300,500,10)
print(x)
z = x.reshape(4,5)
print(z)

[300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450 460 470
 480 490]
[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [28]:
x = np.random.randint(-1000,1000, (20,20))
print(x)
print(x.max())
print(x.min())

[[-900  854  798 -874    1 -479  695 -489 -382 -978 -289 -507  282  534
  -531 -176  741  222  -71 -444]
 [-233 -120  822  901   30  362 -922  554 -225  923  691 -645  380  780
  -415  593  681 -590 -420  926]
 [-524 -348  544  -94  972  958  -19  503 -562   -1  -87 -881  833  898
   433 -740  146  234  180  498]
 [-120  371 -506 -753  503 -816  949  433  804 -883 -591   67 -705 -764
   852  871 -969  626 -901  825]
 [ 971  104  907  576 -587  -28 -203 -241  968  981  548  -38  700  540
  -616 -886  621 -692  423  330]
 [ 528  325  772   19 -187 -552 -678  150 -537 -321  844  514   76 -151
   315  551  766   32 -278 -153]
 [-770 -328 -919 -501 -529  263  480 -598  -43 -140  935 -438  143  263
  -420  -41  867 -829  139 -913]
 [ 474  737 -711  171 -485  927  698 -329 -986  893 -528 -741  -36 -367
  -952  -53   -9   27 -788 -329]
 [  53  959 -411 -966 -376  417 -227 -595  946 -460 -834 -246   71 -382
    57   -5 -375  606 -161   95]
 [ 698  314 -600 -450 -807 -753 -742  852  264  312  -2

# 4. MATHEMATICAL OPERATIONS

In [29]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Add 2 numpy arrays together
z = x+y
z

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
sq = x**2
sq

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [33]:
sqrt = np.sqrt(sq)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
ex = np.exp(y)
ex

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [35]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [36]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [37]:
# Access specific index from the numpy array
x[0]

20

In [38]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[:-2]

array([20, 40, 50])

In [39]:
# Broadcasting, altering several values in a numpy array at once
x[:2] = 10
x

array([10, 10, 50, 21, 15])

In [40]:
# Let's define a two dimensional numpy array
mt = np.random.randint(1,10,(5,5))
mt

array([[2, 6, 6, 7, 6],
       [2, 8, 1, 9, 3],
       [5, 3, 9, 3, 3],
       [3, 2, 9, 6, 6],
       [9, 3, 2, 2, 7]])

In [41]:
# Get a row from a mtrix
mt[1]

array([2, 8, 1, 9, 3])

In [42]:
# Get one element
mt[1][2]

1

In [43]:
mini_matrix = mt[:3]
mini_matrix

array([[2, 6, 6, 7, 6],
       [2, 8, 1, 9, 3],
       [5, 3, 9, 3, 3]])

In [44]:
mini_matrix = mt[2:]
mini_matrix

array([[5, 3, 9, 3, 3],
       [3, 2, 9, 6, 6],
       [9, 3, 2, 2, 7]])

In [45]:
mini_matrix = mt[:, :2]
mini_matrix

array([[2, 6],
       [2, 8],
       [5, 3],
       [3, 2],
       [9, 3]])

In [46]:
mini_matrix = mt[:, 2:]
mini_matrix

array([[6, 7, 6],
       [1, 9, 3],
       [9, 3, 3],
       [9, 6, 6],
       [2, 2, 7]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

In [47]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [48]:
X[-1] = -1
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

In [49]:
X[:2, -2:] = X[:2, -2:] * 2
X 

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [-1, -1, -1, -1, -1]])

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [50]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [51]:
X[X<0] = 0
X[X%2 != 0] = 25
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [52]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [53]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value: 1000


array([752, 643, 980,  62,  53, 582, 909, 987, 823, 886, 682, 124, 168,
       920, 842, 904,  20, 504, 904, 760])

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [54]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [55]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [56]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[ 677  101  462  560 -271  485 -332  423  404  -47  622  222  -96  160
  -962  450  -62  799 -812  624]
 [-651 -329  431  834 -893  497 -856  882 -401 -903  791  421 -904 -119
  -520  -26 -255  225  702  320]
 [ 929  -57 -224 -538  312  370 -326 -969  398  998  741  392 -466 -132
  -448  814  182 -165   11  724]
 [  20  228 -303  493  411 -240  844  284  -95  960   -6 -518  550 -237
   719 -326 -419   10  -84  -56]
 [  64  297  823 -681 -337  943  576 -365  -94  622 -642   28 -745 -952
   693  535 -131  799 -390  233]
 [-801  263  248 -219 -514 -585 -101 -267 -896  554 -843  920 -135  946
  -682 -147    2 -170 -208  -61]
 [-484 -633    5  782 -219  996  677 -307   65  -20 -587  317 -185  711
  -463  934  675  384 -829 -117]
 [-955 -866 -107  428  360  732  628 -638 -717 -550  380 -145 -629 -996
  -826  618 -398 -272  386  317]
 [ 486  582 -205 -621 -703  437 -962 -919  -75 -557 -138   66 -939  -97
     5 -569 -730  409  203 -868]
 [ 802  145  298 -432 -396 -948  433  957    6  131  64

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [57]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [58]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [59]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [60]:
X[:2, 3:]  = X[:2, 3:] * 2

In [61]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [62]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])